/**
 * Master catalog of all 46 Canonical Vital Elements from SIMPLEX HIMES Master V9.3
 * Reference: https://staging.simplexworld.com/MasterV9.3/editEMRVital/panel_1_1_0
 */

export type VitalBasis = 'V' | 'T' | 'P'; // Visit Based | Time Based | Patient Based

export interface VitalElementDef {
  elementId: number;
  code: string; // 'element_1', 'element_2', ...
  name: string;
  category: 'vital' | 'anthropometry' | 'screening' | 'triage' | 'respiratory' | 'hemodialysis' | 'nursing' | 'pain' | 'neurological' | 'obstetric' | 'ophthalmology' | 'renal';
  uom?: string;
  defaultBasis: VitalBasis;
  defaultRequired: boolean;
  icon?: string;
  normalRange?: { from: number; to: number; unit: string };
  options?: string[];
  description?: string;
}

export interface ConfiguredVitalElement {
  code: string;
  elementId: number;
  name: string;
  basis: VitalBasis; // 'V' | 'T' | 'P'
  isRequired: boolean;
  order: number;
}

/** Complete catalog of all 46 elements from SIMPLEX HIMES */
export const VITAL_ELEMENTS_CATALOG: VitalElementDef[] = [
  {
    elementId: 1,
    code: 'element_1',
    name: 'Body Temperature',
    category: 'vital',
    uom: '°C',
    defaultBasis: 'V',
    defaultRequired: true,
    icon: 'fa-solid fa-temperature-half',
    normalRange: { from: 36.1, to: 37.5, unit: '°C' },
    description: 'Oral/axillary/tympanic core temperature in Celsius or Fahrenheit',
  },
  {
    elementId: 2,
    code: 'element_2',
    name: 'Height, Weight and BMI Index',
    category: 'anthropometry',
    uom: 'kg/m²',
    defaultBasis: 'P',
    defaultRequired: true,
    icon: 'fa-solid fa-weight-scale',
    normalRange: { from: 18.5, to: 24.9, unit: 'kg/m²' },
    description: 'Height in cm, Weight in kg, automated Quetelet BMI computation',
  },
  {
    elementId: 3,
    code: 'element_3',
    name: 'Blood Pressure',
    category: 'vital',
    uom: 'mmHg',
    defaultBasis: 'V',
    defaultRequired: true,
    icon: 'fa-solid fa-heart-pulse',
    normalRange: { from: 90, to: 120, unit: 'mmHg (Systolic)' },
    description: 'Systolic and Diastolic non-invasive arterial pressure in mmHg',
  },
  {
    elementId: 4,
    code: 'element_4',
    name: 'Pulse Rate',
    category: 'vital',
    uom: '/min',
    defaultBasis: 'V',
    defaultRequired: true,
    icon: 'fa-solid fa-wave-square',
    normalRange: { from: 60, to: 100, unit: 'beats/min' },
    description: 'Radial/apical pulse rate per minute with age-category context',
  },
  {
    elementId: 5,
    code: 'element_5',
    name: 'Blood Sugar',
    category: 'vital',
    uom: 'mg/dL',
    defaultBasis: 'V',
    defaultRequired: false,
    icon: 'fa-solid fa-droplet',
    normalRange: { from: 70, to: 140, unit: 'mg/dL' },
    description: 'Random/Fasting/Post-prandial capillary blood glucose',
  },
  {
    elementId: 6,
    code: 'element_6',
    name: 'Waist Circumference',
    category: 'anthropometry',
    uom: 'cm',
    defaultBasis: 'P',
    defaultRequired: false,
    icon: 'fa-solid fa-ruler-horizontal',
    normalRange: { from: 60, to: 94, unit: 'cm' },
    description: 'Abdominal perimeter at midpoint between lower rib and iliac crest',
  },
  {
    elementId: 7,
    code: 'element_7',
    name: 'SpO2',
    category: 'vital',
    uom: '%',
    defaultBasis: 'V',
    defaultRequired: true,
    icon: 'fa-solid fa-lungs',
    normalRange: { from: 95, to: 100, unit: '%' },
    description: 'Peripheral arterial oxygen saturation via pulse oximeter',
  },
  {
    elementId: 8,
    code: 'element_8',
    name: 'Respiratory Rate',
    category: 'vital',
    uom: '/min',
    defaultBasis: 'V',
    defaultRequired: true,
    icon: 'fa-solid fa-wind',
    normalRange: { from: 12, to: 20, unit: 'breaths/min' },
    description: 'Spontaneous respirations counted per full minute',
  },
  {
    elementId: 9,
    code: 'element_9',
    name: 'Hips Circumference',
    category: 'anthropometry',
    uom: 'cm',
    defaultBasis: 'P',
    defaultRequired: false,
    icon: 'fa-solid fa-ruler',
    description: 'Maximal circumference around the buttocks / greater trochanters',
  },
  {
    elementId: 10,
    code: 'element_10',
    name: 'Reason For Visit',
    category: 'triage',
    defaultBasis: 'V',
    defaultRequired: false,
    icon: 'fa-solid fa-clipboard-question',
    description: 'Primary clinical presenting reason or chief symptom for encounter',
  },
  {
    elementId: 11,
    code: 'element_11',
    name: 'Pregnancy',
    category: 'obstetric',
    defaultBasis: 'P',
    defaultRequired: false,
    icon: 'fa-solid fa-person-pregnant',
    options: ['Not Pregnant', '1st Trimester', '2nd Trimester', '3rd Trimester', 'Postpartum', 'Uncertain'],
    description: 'Maternal gestational status and trimester evaluation',
  },
  {
    elementId: 12,
    code: 'element_12',
    name: 'Vital Element Pain Score',
    category: 'pain',
    defaultBasis: 'V',
    defaultRequired: false,
    icon: 'fa-solid fa-face-frown',
    options: ['Yes', 'No'],
    description: 'Binary triage question: Now patient has pain? (Yes / No)',
  },
  {
    elementId: 13,
    code: 'element_13',
    name: 'Nutritional Assessment',
    category: 'screening',
    defaultBasis: 'P',
    defaultRequired: false,
    icon: 'fa-solid fa-apple-whole',
    options: ['Well Nourished', 'Mild Malnutrition', 'Moderate Malnutrition', 'Severe Malnutrition'],
    description: 'Clinical subjective nutritional status assessment',
  },
  {
    elementId: 14,
    code: 'element_14',
    name: 'Fall Risk Screening',
    category: 'nursing',
    defaultBasis: 'V',
    defaultRequired: false,
    icon: 'fa-solid fa-person-falling',
    options: ['Low Risk (0-24)', 'Medium Risk (25-50)', 'High Risk (>50)'],
    description: 'Morse Fall Scale / Hendrich II fall risk assessment',
  },
  {
    elementId: 15,
    code: 'element_15',
    name: 'Patient Caregiver Education',
    category: 'nursing',
    defaultBasis: 'V',
    defaultRequired: false,
    icon: 'fa-solid fa-chalkboard-user',
    options: ['Understood', 'Needs Reinforcement', 'Caregiver Informed', 'Barrier to Learning', 'Refused'],
    description: 'Discharge/medication instructions comprehension check',
  },
  {
    elementId: 16,
    code: 'element_16',
    name: 'Vital Pain Score',
    category: 'pain',
    defaultBasis: 'V',
    defaultRequired: true,
    icon: 'fa-solid fa-face-smile',
    options: ['0 - No Hurt', '2 - Hurts Little Bit', '4 - Hurts Little More', '6 - Hurts Even More', '8 - Hurts Whole Lot', '10 - Hurts Worst'],
    description: 'Wong-Baker FACES pain rating scale (0–10) with smiley emoticons',
  },
  {
    elementId: 17,
    code: 'element_17',
    name: 'BMI Growth Chart',
    category: 'anthropometry',
    defaultBasis: 'P',
    defaultRequired: false,
    icon: 'fa-solid fa-chart-line',
    description: 'WHO/CDC pediatric age-and-gender standardized BMI percentile curve',
  },
  {
    elementId: 18,
    code: 'element_18',
    name: 'Adult Nutritional Screening Tool',
    category: 'screening',
    defaultBasis: 'P',
    defaultRequired: false,
    icon: 'fa-solid fa-utensils',
    options: ['Score 0 (Low Risk)', 'Score 1 (Medium Risk)', 'Score 2+ (High Risk)'],
    description: 'Malnutrition Universal Screening Tool (MUST) score',
  },
  {
    elementId: 19,
    code: 'element_19',
    name: 'Chest Inspiration & Expiration',
    category: 'respiratory',
    uom: 'cm',
    defaultBasis: 'V',
    defaultRequired: false,
    icon: 'fa-solid fa-arrows-left-right',
    description: 'Thoracic excursion difference between maximal inspiration and expiration',
  },
  {
    elementId: 20,
    code: 'element_20',
    name: 'Abdominal girth',
    category: 'anthropometry',
    uom: 'cm',
    defaultBasis: 'V',
    defaultRequired: false,
    icon: 'fa-solid fa-circle-notch',
    description: 'Serial abdominal girth measurement for ascites or distention',
  },
  {
    elementId: 21,
    code: 'element_21',
    name: 'CTAS Triage Level',
    category: 'triage',
    defaultBasis: 'V',
    defaultRequired: false,
    icon: 'fa-solid fa-triangle-exclamation',
    options: ['Level 1 - Resuscitation', 'Level 2 - Emergent', 'Level 3 - Urgent', 'Level 4 - Less Urgent', 'Level 5 - Non Urgent'],
    description: 'Canadian Triage and Acuity Scale acuity tier',
  },
  {
    elementId: 22,
    code: 'element_22',
    name: 'Triage Intervention',
    category: 'triage',
    defaultBasis: 'V',
    defaultRequired: false,
    icon: 'fa-solid fa-kit-medical',
    options: ['Immediate Resuscitation', 'Oxygen Administered', 'IV Access Established', 'ECG Performed', 'C-Spine Immobilized', 'Nebulization', 'Analgesia Administered'],
    description: 'Stat clinical interventions initiated in triage bay',
  },
  {
    elementId: 23,
    code: 'element_23',
    name: 'Triage Dispostion',
    category: 'triage',
    defaultBasis: 'V',
    defaultRequired: false,
    icon: 'fa-solid fa-arrow-right-arrow-left',
    options: ['Resuscitation Room', 'Major / Acute Bed', 'Subacute Area', 'Fast Track / Minor', 'Waiting Area', 'Direct IP Admission'],
    description: 'Designated physical emergency treatment area',
  },
  {
    elementId: 24,
    code: 'element_24',
    name: 'Triage Status',
    category: 'triage',
    defaultBasis: 'V',
    defaultRequired: false,
    icon: 'fa-solid fa-clock',
    options: ['Triaged', 'Waiting for Physician', 'In Consultation', 'Re-triaged', 'Discharged from Triage'],
    description: 'Current tracking status of patient within ED triage stream',
  },
  {
    elementId: 25,
    code: 'element_25',
    name: 'Sedation Score',
    category: 'neurological',
    defaultBasis: 'T',
    defaultRequired: false,
    icon: 'fa-solid fa-bed',
    options: ['+4 Combative', '+3 Very Agitated', '+2 Agitated', '+1 Restless', '0 Alert and Calm', '-1 Drowsy', '-2 Light Sedation', '-3 Moderate Sedation', '-4 Deep Sedation', '-5 Unarousable'],
    description: 'Richmond Agitation-Sedation Scale (RASS) score',
  },
  {
    elementId: 26,
    code: 'element_26',
    name: 'Flacc',
    category: 'pain',
    defaultBasis: 'V',
    defaultRequired: false,
    icon: 'fa-solid fa-baby',
    options: ['0 - Relaxed and Comfortable', '1-3 - Mild Discomfort', '4-6 - Moderate Pain', '7-10 - Severe Discomfort or Pain'],
    description: 'Face, Legs, Activity, Cry, Consolability pediatric pain tool',
  },
  {
    elementId: 27,
    code: 'element_27',
    name: 'Consciousness(AVPU)',
    category: 'neurological',
    defaultBasis: 'V',
    defaultRequired: false,
    icon: 'fa-solid fa-head-side-virus',
    options: ['A - Alert', 'V - Voice Responding', 'P - Pain Responding', 'U - Unresponsive'],
    description: 'Rapid neurological consciousness level scale',
  },
  {
    elementId: 28,
    code: 'element_28',
    name: 'EWS Score',
    category: 'vital',
    defaultBasis: 'T',
    defaultRequired: false,
    icon: 'fa-solid fa-gauge-high',
    normalRange: { from: 0, to: 3, unit: 'pts' },
    description: 'National Early Warning Score (NEWS2) aggregate deterioration index',
  },
  {
    elementId: 29,
    code: 'element_29',
    name: 'BSA',
    category: 'anthropometry',
    uom: 'm²',
    defaultBasis: 'P',
    defaultRequired: false,
    icon: 'fa-solid fa-child-reaching',
    description: 'Body Surface Area in m² via Mosteller formula √(Ht × Wt / 3600)',
  },
  {
    elementId: 30,
    code: 'element_30',
    name: 'Any supplemental Oxygen',
    category: 'respiratory',
    defaultBasis: 'V',
    defaultRequired: false,
    icon: 'fa-solid fa-mask-ventilator',
    options: ['None (Room Air)', 'Nasal Cannula (1-4 L/min)', 'Simple Face Mask (5-10 L/min)', 'Non-Rebreather (10-15 L/min)', 'Venturi Mask', 'High-Flow Nasal Cannula', 'NIV / BiPAP', 'Invasive Mechanical Ventilation'],
    description: 'Mode of supplemental oxygen delivery and flow titration',
  },
  {
    elementId: 31,
    code: 'element_31',
    name: 'Capillary Refill',
    category: 'vital',
    uom: 'sec',
    defaultBasis: 'V',
    defaultRequired: false,
    icon: 'fa-solid fa-stopwatch',
    options: ['Normal (< 2 seconds)', 'Prolonged / Delayed (> 2 seconds)', 'Sluggish'],
    description: 'Peripheral microvascular perfusion refill time after blanching',
  },
  {
    elementId: 32,
    code: 'element_32',
    name: 'Neglect History',
    category: 'nursing',
    defaultBasis: 'P',
    defaultRequired: false,
    icon: 'fa-solid fa-user-shield',
    options: ['No Signs of Neglect / Abuse', 'Suspected Vulnerability / Neglect', 'Documented Protective Service Alert'],
    description: 'Vulnerable patient safeguarding and social risk screening',
  },
  {
    elementId: 33,
    code: 'element_33',
    name: 'Allergy',
    category: 'vital',
    defaultBasis: 'P',
    defaultRequired: true,
    icon: 'fa-solid fa-shield-virus',
    description: 'Drug, Food, Environment and Contrast agent allergies listing',
  },
  {
    elementId: 34,
    code: 'element_34',
    name: 'Visual Acuity',
    category: 'ophthalmology',
    defaultBasis: 'P',
    defaultRequired: false,
    icon: 'fa-solid fa-eye',
    description: 'Distance vision test (OD, OS, OU) via standard Snellen / LogMAR',
  },
  {
    elementId: 35,
    code: 'element_35',
    name: 'Chest Circumference',
    category: 'anthropometry',
    uom: 'cm',
    defaultBasis: 'P',
    defaultRequired: false,
    icon: 'fa-solid fa-tape',
    description: 'Infant/pediatric chest perimeter at xiphoid process level',
  },
  {
    elementId: 36,
    code: 'element_36',
    name: 'Head Circumference',
    category: 'anthropometry',
    uom: 'cm',
    defaultBasis: 'P',
    defaultRequired: false,
    icon: 'fa-solid fa-brain',
    normalRange: { from: 32, to: 52, unit: 'cm' },
    description: 'Fronto-occipital head circumference for pediatric growth monitoring',
  },
  {
    elementId: 37,
    code: 'element_37',
    name: 'Blood Flow Rate',
    category: 'hemodialysis',
    uom: 'mL/min',
    defaultBasis: 'T',
    defaultRequired: false,
    icon: 'fa-solid fa-arrow-right-arrow-left',
    normalRange: { from: 200, to: 500, unit: 'mL/min' },
    description: 'Hemodialysis extracorporeal blood pump flow rate (Qb)',
  },
  {
    elementId: 38,
    code: 'element_38',
    name: 'Venous Pressure',
    category: 'hemodialysis',
    uom: 'mmHg',
    defaultBasis: 'T',
    defaultRequired: false,
    icon: 'fa-solid fa-gauge',
    normalRange: { from: 50, to: 200, unit: 'mmHg' },
    description: 'Dialysis venous return line bubble trap pressure (Vp)',
  },
  {
    elementId: 39,
    code: 'element_39',
    name: 'Arterial Pressure',
    category: 'hemodialysis',
    uom: 'mmHg',
    defaultBasis: 'T',
    defaultRequired: false,
    icon: 'fa-solid fa-gauge-simple',
    normalRange: { from: -200, to: -50, unit: 'mmHg' },
    description: 'Pre-pump arterial inlet access negative pressure (Ap)',
  },
  {
    elementId: 40,
    code: 'element_40',
    name: 'Ultrafiltration Rate',
    category: 'hemodialysis',
    uom: 'mL/hr',
    defaultBasis: 'T',
    defaultRequired: false,
    icon: 'fa-solid fa-filter',
    normalRange: { from: 100, to: 1500, unit: 'mL/hr' },
    description: 'Prescribed hourly fluid removal rate across dialyzer membrane',
  },
  {
    elementId: 41,
    code: 'element_41',
    name: 'Actual Ultrafiltration Volume',
    category: 'hemodialysis',
    uom: 'mL',
    defaultBasis: 'T',
    defaultRequired: false,
    icon: 'fa-solid fa-flask-vial',
    description: 'Cumulative total fluid volume removed during dialysis session',
  },
  {
    elementId: 42,
    code: 'element_42',
    name: 'Emergency(ESI) Level',
    category: 'triage',
    defaultBasis: 'V',
    defaultRequired: false,
    icon: 'fa-solid fa-truck-medical',
    options: ['ESI 1 - Resuscitation', 'ESI 2 - Emergent', 'ESI 3 - Urgent (≥2 resources)', 'ESI 4 - Less Urgent (1 resource)', 'ESI 5 - Non-Urgent (0 resources)'],
    description: 'Emergency Severity Index 5-level triage acuity protocol',
  },
  {
    elementId: 43,
    code: 'element_43',
    name: 'Emergency(ESI) Status',
    category: 'triage',
    defaultBasis: 'V',
    defaultRequired: false,
    icon: 'fa-solid fa-bell',
    options: ['Active Assessment', 'Resource Planning', 'Secondary Triage Complete', 'Bed Assigned', 'Transferred to OT/ICU'],
    description: 'Progress status of patient undergoing ESI pathway',
  },
  {
    elementId: 44,
    code: 'element_44',
    name: 'Respiratory Distress',
    category: 'respiratory',
    defaultBasis: 'V',
    defaultRequired: false,
    icon: 'fa-solid fa-stethoscope',
    options: ['None (Eupneic)', 'Mild (Tachypnea without retractions)', 'Moderate (Subcostal retractions, nasal flaring)', 'Severe (Sternocleidomastoid use, grunting, paradoxical breathing)'],
    description: 'Clinical respiratory distress scoring and accessory muscle use',
  },
  {
    elementId: 45,
    code: 'element_45',
    name: 'Respiratory Support',
    category: 'respiratory',
    defaultBasis: 'V',
    defaultRequired: false,
    icon: 'fa-solid fa-fan',
    options: ['Room Air', 'Low-Flow O2 (1-6 L/min)', 'High-Flow Nasal Cannula (HFNC)', 'CPAP', 'BiPAP / NIV', 'Invasive SIMV/PRVC Ventilation', 'Tracheostomy Collar'],
    description: 'Mechanical respiratory support and ventilatory parameters',
  },
  {
    elementId: 46,
    code: 'element_46',
    name: 'Urine Output mLs/hr',
    category: 'renal',
    uom: 'mL/hr',
    defaultBasis: 'T',
    defaultRequired: false,
    icon: 'fa-solid fa-faucet-drip',
    normalRange: { from: 30, to: 100, unit: 'mL/hr' },
    description: 'Foley or voided urine output monitored hourly for oliguria check',
  },
];

/** Default 12 selected elements matching Simplex HIMES initial configuration */
export const DEFAULT_SELECTED_VITAL_ELEMENTS: ConfiguredVitalElement[] = [
  { code: 'element_1', elementId: 1, name: 'Body Temperature', basis: 'V', isRequired: true, order: 1 },
  { code: 'element_33', elementId: 33, name: 'Allergy', basis: 'P', isRequired: true, order: 2 },
  { code: 'element_3', elementId: 3, name: 'Blood Pressure', basis: 'V', isRequired: true, order: 3 },
  { code: 'element_4', elementId: 4, name: 'Pulse Rate', basis: 'V', isRequired: true, order: 4 },
  { code: 'element_5', elementId: 5, name: 'Blood Sugar', basis: 'V', isRequired: false, order: 5 },
  { code: 'element_6', elementId: 6, name: 'Waist Circumference', basis: 'P', isRequired: false, order: 6 },
  { code: 'element_7', elementId: 7, name: 'SpO2', basis: 'V', isRequired: true, order: 7 },
  { code: 'element_8', elementId: 8, name: 'Respiratory Rate', basis: 'V', isRequired: true, order: 8 },
  { code: 'element_12', elementId: 12, name: 'Vital Element Pain Score', basis: 'V', isRequired: false, order: 9 },
  { code: 'element_9', elementId: 9, name: 'Hips Circumference', basis: 'P', isRequired: false, order: 10 },
  { code: 'element_16', elementId: 16, name: 'Vital Pain Score', basis: 'V', isRequired: true, order: 11 },
  { code: 'element_2', elementId: 2, name: 'Height, Weight and BMI Index', basis: 'P', isRequired: true, order: 12 },
];

const STORAGE_KEY_PREFIX = 'himes_vital_panel_config_';

/** Load configured elements for a given panel/form, or return the standard 12 defaults */
export function loadConfiguredVitalElements(formId: string | number = '1'): ConfiguredVitalElement[] {
  try {
    const raw = localStorage.getItem(`${STORAGE_KEY_PREFIX}${formId}`);
    if (raw) {
      const parsed = JSON.parse(raw);
      if (Array.isArray(parsed) && parsed.length > 0) {
        return parsed;
      }
    }
  } catch {
    /* fallback */
  }
  return DEFAULT_SELECTED_VITAL_ELEMENTS;
}

/** Save configured elements for a given panel/form */
export function saveConfiguredVitalElements(formId: string | number, elements: ConfiguredVitalElement[]): void {
  try {
    localStorage.setItem(`${STORAGE_KEY_PREFIX}${formId}`, JSON.stringify(elements));
  } catch {
    /* ignore */
  }
}
