import * as pdf from 'html-pdf';
import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import { execFile } from 'child_process';

export type PdfOptions = pdf.CreateOptions;
export type FileInfo = pdf.FileInfo;

function getChromeExecutable(): string | null {
    const candidates = [
        process.env.CHROME_BIN || '',
        '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
        '/Applications/Chromium.app/Contents/MacOS/Chromium',
        '/usr/bin/google-chrome',
        '/usr/bin/google-chrome-stable',
        '/usr/bin/chromium-browser',
        '/usr/bin/chromium',
        'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',
        'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe'
    ];
    for (let i = 0; i < candidates.length; i++) {
        const c = candidates[i];
        if (c && fs.existsSync(c)) {
            return c;
        }
    }
    return null;
}

function runChromeHeadlessPdf(html: string, outputPdfPath: string): Promise<void> {
    const chrome = getChromeExecutable();
    if (!chrome) {
        return Promise.reject(new Error('Chrome executable not found'));
    }

    return new Promise<void>((resolve, reject) => {
        const rnd = Math.random().toString(36).slice(2);
        const tempHtmlPath = path.join(os.tmpdir(), 'hims_pdf_' + Date.now() + '_' + rnd + '.html');
        fs.writeFile(tempHtmlPath, html, 'utf8', (writeErr) => {
            if (writeErr) return reject(writeErr);

            const args = [
                '--headless',
                '--disable-gpu',
                '--no-sandbox',
                '--run-all-compositor-stages-before-draw',
                '--no-pdf-header-footer',
                '--print-to-pdf=' + outputPdfPath,
                tempHtmlPath
            ];

            execFile(chrome, args, { timeout: 30000 }, (execErr) => {
                // Clean up temporary HTML file
                try { fs.unlinkSync(tempHtmlPath); } catch (_) { }

                if (execErr) {
                    return reject(execErr);
                }
                if (!fs.existsSync(outputPdfPath)) {
                    return reject(new Error('PDF output file was not generated by Chrome'));
                }
                return resolve();
            });
        });
    });
}

export class HtmlToPdf {

    public static async CreatePdf(html: string, options: pdf.CreateOptions): Promise<pdf.FileInfo> {
        const chrome = getChromeExecutable();
        if (chrome) {
            const rnd = Math.random().toString(36).slice(2);
            const tempPdf = path.join(os.tmpdir(), 'hims_report_' + Date.now() + '_' + rnd + '.pdf');
            try {
                await runChromeHeadlessPdf(html, tempPdf);
                return { filename: tempPdf };
            } catch (chromeErr) {
                console.warn('Chrome headless PDF generation failed, falling back to html-pdf:', chromeErr);
            }
        }

        return new Promise<pdf.FileInfo>((resolver, reject) => {
            let callback = (err: Error, res: pdf.FileInfo) => {
                if (err) {
                    return reject(err);
                }
                return resolver(res);
            };
            HtmlToPdf.Create(html, options).toFile(callback);
        });
    }

    public static async CreatePdfFile(html: string, options: pdf.CreateOptions, fileName: string): Promise<pdf.FileInfo> {
        const chrome = getChromeExecutable();
        if (chrome) {
            try {
                const dir = path.dirname(fileName);
                if (!fs.existsSync(dir)) {
                    try { fs.mkdirSync(dir); } catch (_) { }
                }
                await runChromeHeadlessPdf(html, fileName);
                return { filename: fileName };
            } catch (chromeErr) {
                console.warn('Chrome headless PDF file generation failed, falling back to html-pdf:', chromeErr);
            }
        }

        return new Promise<pdf.FileInfo>((resolver, reject) => {
            let callback = (err: Error, res: pdf.FileInfo) => {
                if (err) {
                    return reject(err);
                }
                return resolver(res);
            };
            HtmlToPdf.Create(html, options).toFile(fileName, callback);
        });
    }

    public static async CreatePdfStream(html: string, options: pdf.CreateOptions): Promise<fs.ReadStream> {
        const chrome = getChromeExecutable();
        if (chrome) {
            const rnd = Math.random().toString(36).slice(2);
            const tempPdf = path.join(os.tmpdir(), 'hims_stream_' + Date.now() + '_' + rnd + '.pdf');
            try {
                await runChromeHeadlessPdf(html, tempPdf);
                return fs.createReadStream(tempPdf);
            } catch (chromeErr) {
                console.warn('Chrome headless PDF stream failed, falling back to html-pdf:', chromeErr);
            }
        }

        return new Promise<fs.ReadStream>((resolver, reject) => {
            let callback = (err: Error, res: fs.ReadStream) => {
                if (err) {
                    return reject(err);
                }
                return resolver(res);
            };
            HtmlToPdf.Create(html, options).toStream(callback);
        });
    }

    public static async CreatePdfBuffer(html: string, options: pdf.CreateOptions): Promise<Buffer> {
        const chrome = getChromeExecutable();
        if (chrome) {
            const rnd = Math.random().toString(36).slice(2);
            const tempPdf = path.join(os.tmpdir(), 'hims_buf_' + Date.now() + '_' + rnd + '.pdf');
            try {
                await runChromeHeadlessPdf(html, tempPdf);
                const buf = fs.readFileSync(tempPdf);
                try { fs.unlinkSync(tempPdf); } catch (_) { }
                return buf;
            } catch (chromeErr) {
                console.warn('Chrome headless PDF buffer failed, falling back to html-pdf:', chromeErr);
            }
        }

        return new Promise<Buffer>((resolver, reject) => {
            let callback = (err: Error, res: Buffer) => {
                if (err) {
                    return reject(err);
                }
                return resolver(res);
            };
            HtmlToPdf.Create(html, options).toBuffer(callback);
        });
    }

    public static Create(html: string, options: pdf.CreateOptions): pdf.CreateResult {
        return pdf.create(html, options);
    }
}
